### ISSUE TITLE
Support a robust binary geometry format (PLY?)

### ISSUE THREAD

**Issue by gkjohnson** [ros/urdf#12]
Hello! I'm not sure if this is the right place for a suggestion like this, but maybe someone can point me in the right direction otherwise.

The URDF spec only mentions support for both [.DAE and .STL file formats](http://wiki.ros.org/urdf/XML/link) in the `<mesh>` tag, but STL is pretty limited in terms of what it can store and Collada doesn't support a binary format, so it winds up being pretty bloated. My suggestion is [.PLY, which is a pretty flexible format](http://paulbourke.net/dataformats/ply/) and one I've been using for variety of projects and supports texture coordinates and vertex colors.

Thoughts?

And if this isn't the right place to discuss extensions to the spec, let me know!

Thanks!

**Comment by sloretz** [comment]
Linking to discussion at https://discourse.ros.org/t/support-the-ply-geometry-format-in-urdf/4325/5

**Comment by gkjohnson** [comment]
The URDF spec wiki has been updated to reflect that URDF supports any mesh format with specific application compatibility dependent on implementation:

http://wiki.ros.org/urdf/XML/link

See discussion here:

https://discourse.ros.org/t/web-based-urdf-visualization-tool-and-library-opensourced-from-nasa-jpl/14404/2
