### ISSUE TITLE
Specifying the location for mesh (*.obj, *,DAE) files as a relative path w/o referencing ros package

### ISSUE THREAD

**Issue by mch5048** [ros/urdf#36]
Hi, currently I am building a custom IK solver that is running independently with ROS and it utilizes urdf parser.

To my knowledge, the specification for the mesh files can have the form of 

package:// that finds the ROS package for robot description or files:// that specifies the absolute path to the mesh files.

Can there be an alternative for the relative import of the mesh files?

Thanks in advance!

**Comment by Jaeyoung-Lim** [comment]
@mch5048 If you use either `GAZEBO_RESOURCE_PATH` or `GAZEBO_MODEL_PATH` you can use the tag `model://` for the context of using mesh files in gazebo. 

Does this answer your question?

**Comment by mch5048** [comment]
@Jaeyoung-Lim Thanks for the quick reply! Unfortunately, I think I posted the question in the wrong place.

I am using  [pinocchio](https://github.com/stack-of-tasks/pinocchio) package and its urdf parsing seems 
customized [here](https://github.com/stack-of-tasks/pinocchio/blob/a1df23c2f183d84febdc2099e5fbfdbd1fc8018b/src/parsers/utils.hpp#L76
).
It seems only the `file://` or` package ://` is supported for this package as of now.

Based on the information on the GAZEBO environment path,  think I can customize this header file to find my own type of 
tag that points to the relative path to mesh.

Thank you!
